VulnTech_V3/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vt_site.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'vt_site.views.handel404'

ide/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', editor_view, name='ide'),
]

tutorial/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.tutorial, name='tutorial'),
    path('<slug:slug>/<slug:lesson_slug>/', views.tutorial_content, name='tutorial_content'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vt_site/urls.py
from django.conf import settings
from django.urls import include, path
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contactUs', views.contact, name='contact'),
    path('plans', views.plans, name='plans'),
    path('maintenance', views.maintenance, name='maintenance'),
    path('faq', views.faq, name='faq'),
    path('terms_pages/<slug:slug>', views.privacy, name='terms_pages'),
    path('tutorial/', include('tutorial.urls')),
    path('courses/', include('video_courses.urls')),
    path('accounts/', include('account.urls')),
    path('compiler/', include('ide.urls'), name='ide'),
    path('dashboard/', views.my_dashboard, name='my_dashboard'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from functools import partial
import os

def validate_file_extension(file, allowed_extensions):
    ext = os.path.splitext(file.name)[1].lower()
    if ext not in allowed_extensions:
        raise ValidationError(f"Unsupported file extension. Allowed extensions are: {', '.join(allowed_extensions)}")

validate_image = partial(validate_file_extension, allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.bmp'])


class tutorial_category(models.Model):
    icon = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=200)
    desc = models.CharField(max_length=500, null=True)
    image = models.ImageField(upload_to='media/tutorial_category', null=True, validators=[validate_image])

    def __str__(self) -> str:
        return self.name

class Tutorial(models.Model):
    status = (
        ('upcoming', 'upcoming'),
        ('trending', 'trending'),
        ('none', 'none')
    )
    image = models.ImageField(upload_to='media/tutorial_imgs', null=True, validators=[validate_image])
    title = models.CharField(max_length=500)
    category = models.ForeignKey(tutorial_category,on_delete=models.CASCADE)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=status,max_length=100,null=True)

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        first_lesson = tutorials_Lesson.objects.filter(chapter__tutorial=self).first()
        if first_lesson:
            return reverse("tutorial_content", kwargs={'slug': self.slug, 'lesson_slug': first_lesson.slug})
        return reverse("tutorial_content", kwargs={'slug': self.slug, 'lesson_slug': None})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    model = instance.__class__ 
    res = model.objects.filter(slug=slug).order_by('-id')
    exists = res.exists()
    if exists:
        new_slug = "%s-%s" % (slug, res.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Tutorial)


class tutorial_Chapter(models.Model):
    tutorial = models.ForeignKey(Tutorial, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class tutorials_Lesson(models.Model):
    chapter = models.ForeignKey(tutorial_Chapter, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field.")
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("tutorial_content", kwargs={'slug': self.chapter.tutorial.slug, 'lesson_slug': self.slug})
    
    def get_next_lesson(self):
        next_lesson = self.chapter.tutorials_lesson_set.filter(id__gt=self.id).first()
        return next_lesson

    def get_previous_lesson(self):
        previous_lesson = self.chapter.tutorials_lesson_set.filter(id__lt=self.id).last()
        return previous_lesson
    
pre_save.connect(pre_save_post_receiver, tutorials_Lesson)

tutorial/views.py
from unicodedata import category
from django.shortcuts import get_object_or_404, render

from tutorial.models import *
from vt_site.models import Terms_pages, site_detail


def tutorial(request):
    category = tutorial_category.objects.all().order_by('id')
    tutorials = Tutorial.objects.all()
    trend_tutorials = Tutorial.objects.filter(status = 'trending').order_by('id')[0:8]
    terms_pages = Terms_pages.objects.all()
    siteDetail = site_detail.objects.all()
    context = {
        'tutorials': tutorials,
        'category' : category,
        'trend_tutorials' : trend_tutorials,
        'terms_pages' : terms_pages,
        'siteDetail' : siteDetail,
    }
    return render(request,"tutorial_pages/tutorials.html",context)

def tutorial_content(request, slug, lesson_slug):
    tutorial = get_object_or_404(Tutorial, slug=slug)
    chapters = tutorial.tutorial_chapter_set.all()
    
    if lesson_slug == 'None':
        first_lesson = chapters[0].tutorials_lesson_set.first() if chapters else None
        if first_lesson:
            lesson_slug = first_lesson.slug

    lesson = get_object_or_404(tutorials_Lesson, slug=lesson_slug)
    
    previous_lesson = tutorials_Lesson.objects.filter(chapter__tutorial=tutorial, id__lt=lesson.id).last()
    next_lesson = tutorials_Lesson.objects.filter(chapter__tutorial=tutorial, id__gt=lesson.id).first()
    siteDetail = site_detail.objects.all()
    terms_pages = Terms_pages.objects.all()
    context = {
        'tutorial': tutorial,
        'chapters': chapters,
        'lesson': lesson,
        'slug' : slug,
        'previous_lesson': previous_lesson,
        'next_lesson': next_lesson,
        'terms_pages' : terms_pages,
        'siteDetail' : siteDetail,
    }
    return render(request,"tutorial_pages/tutorial_content.html",context)

vt_site/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.templatetags.static import static
from django.conf import settings as conf_settings
from django.contrib import messages
from tutorial.models import *
from video_courses.models import * 
from video_courses.models import Courses, course_category
from vt_site.models import *
from django.core.mail import send_mail
from django.utils import timezone
from django.http import JsonResponse
from datetime import date, timedelta


def index(request):
    terms_pages = Terms_pages.objects.all()
    tutorialsCategory = tutorial_category.objects.all().order_by('id')[:6]
    coursesCategory = course_category.objects.all().order_by('id')[:6]
    featured_courses = Courses.objects.filter(is_free_course=True).order_by('-id')[:6]
    plans = Plan.objects.all()
    siteDetail = site_detail.objects.all()
    
    context = {
        'tutorialsCategory': tutorialsCategory,
        'coursesCategory': coursesCategory,
        'featured_courses': featured_courses,
        'terms_pages': terms_pages,
        'plans': plans,
        'siteDetail': siteDetail,
    }
    return render(request, "main_elements/index.html", context)

def about(request):
    terms_pages = Terms_pages.objects.all()
    team = Teammate.objects.all()
    siteDetail = site_detail.objects.all()
    context = {
        'terms_pages': terms_pages,
        'team': team,
        'siteDetail': siteDetail,
    }
    return render(request, "main_elements/aboutus.html", context)

def contact(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            name = request.POST['name']
            subject = request.POST['subject']
            content = request.POST['content']

            sub = subject
            msg = f'''Dear VulnTech Team,

{request.user.email} user sent this mail. The message from {name} is below.

{content} 

With regards,
{name}'''
        
            from_email = conf_settings.EMAIL_HOST_USER
            to = conf_settings.DEFAULT_FROM_EMAIL
            try:
                user_feedback_time = request.user.feedback_last_sent_at
                if user_feedback_time is None or user_feedback_time + timezone.timedelta(minutes=15) < timezone.now():
                    send_mail(sub, msg, from_email, [to])
                    messages.success(request, "Form Submitted Successfully")
                    request.user.feedback_last_sent_at = timezone.now()
                    request.user.save()
                else:
                    messages.error(request, "Please wait for 15 minutes between feedback submissions.")
                return redirect('contact')
            except Exception:   
                messages.error(request, "Something went wrong, try again later.")
                return redirect('contact')
        else:
            messages.error(request, "Please log in to submit the form.")
            return redirect('contact')
    else:
        terms_pages = Terms_pages.objects.all()
        siteDetail = site_detail.objects.all()
        context = {
            'terms_pages': terms_pages,
            'siteDetail': siteDetail,
        }
        return render(request, "main_elements/contactus.html", context)

def plans(request):
    terms_pages = Terms_pages.objects.all()
    siteDetail = site_detail.objects.all()
    context = {
        'terms_pages': terms_pages,
        'siteDetail': siteDetail,
    }
    return render(request, "main_elements/plans.html", context)

def maintenance(request):
    return render(request, "maintenance_pages/maintenance.html")

def privacy(request, slug):
    terms_pages = Terms_pages.objects.all()
    terms = get_object_or_404(Terms_pages, slug=slug)
    siteDetail = site_detail.objects.all()
    context = {
        'terms': terms,
        'terms_pages': terms_pages,
        'siteDetail': siteDetail,
    }
    return render(request, "main_elements/terms_pages.html", context)

def handel404(request, exception):
    return render(request, "maintenance/404.html")

def faq(request):
    faq_category = FAQ_cate.objects.all().order_by('id')
    siteDetail = site_detail.objects.all()
    faq = FAQ.objects.all()
    terms_pages = Terms_pages.objects.all()
    context = {
        'faq': faq,
        'faq_category': faq_category,
        'terms_pages': terms_pages,
        'siteDetail': siteDetail,
    }
    return render(request, "main_elements/faq.html", context)

def my_dashboard(request):
    return render(request, 'main_elements/my_dashboard.html')

vt_site/templates/tutorial_pages/tutorial_content.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - {{tutorial.title}} Tutorial{% endblock %}
{% block internal_style %}
<style>
    

    .container {
        max-width: 1800px;
        width: 100% !important;
        
    }
    .tutorial_index {
        background-color: #161616;
    }
    .row {
        max-width: 2000px;
        margin: auto;
        
    }
    .col-lg-3 {
        flex: 0 0 auto;
        width: 23%;
        
    }
    
</style>
{% endblock %}
{% block sm-nav-block %}
        <span class="sm-nav-item">
            <a class="nav-link mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="The usage will be revealed in the future."><i class="fas fa-coins mx-2"></i><span>100</span></a>
            <!-- <a class="nav-link mx-2"><img src="../images/icons-user.png" alt="user" class="img-fluid rounded-circle"></a> -->
            
        </span>
    {% endblock %}
{% block body_content %}

    <section class="pb-5 px-0">
        <div class="container">
            <div class="row py-5">
                <div class="col-12 col-md-4 col-lg-3 mx-0 mx-md-2 px-0 tutorial_index">
                    <ul class="nav flex-column">
                        {% for chapter in chapters %}
                            <li class="nav-item">
                            <span class="nav-link index_title"style="color: #1E1E1E;">{{chapter.title}}</span>
                            </li>

                            {% for i in chapter.tutorials_lesson_set.all %}
                                <li class="nav-item">
                                    <a class="nav-link {% if i.slug == lesson.slug %}active{% endif %}" href="{{i.get_absolute_url}}">{{i.title}}</a>
                                </li>
                            {% endfor %}
                        {% endfor %}
                    </ul>

                </div>

                <div class="col-12 col-md-7 col-lg-6 pt-5 mx-0 mx-md-2 px-2 px-md-5 blog_post-content">
                    <h2 class="blog-post-title">{{ lesson.title }}</h2>
                    <!-- <div class="d-flex justify-content-between align-items-center py-3">
                        <a href="{{lesson.get_absolute_url}}" class="btn btn-primary">Previous</a>
                        <a href="{{i.get_absolute_url}}" class="btn btn-primary">Next</a>
                    </div> -->
                    <div class="d-flex justify-content-between align-items-center py-3">
                        <a href="{% if previous_lesson %}{% url 'tutorial_content' slug=slug lesson_slug=previous_lesson.slug %}{% endif %}" class="btn btn-primary {% if not previous_lesson %}disabled{% endif %}" id="previous-lesson"style="background-color: #DDF247; color: var(--text-color-black);border: none;">Previous</a>
                        <a href="{% if next_lesson %}{% url 'tutorial_content' slug=slug lesson_slug=next_lesson.slug %}{% endif %}" class="btn btn-primary {% if not next_lesson %}disabled{% endif %}" id="next-lesson"style="background-color: #DDF247; color: var(--text-color-black);border: none;">Next</a>
                    </div>
                    
                    

                    <div class="post-content py-3">
                        {{ lesson.content|safe }}
                    </div>

                    <div class="d-flex justify-content-between align-items-center py-3">
                        <a href="{% if previous_lesson %}{% url 'tutorial_content' slug=slug lesson_slug=previous_lesson.slug %}{% endif %}" class="btn btn-primary {% if not previous_lesson %}disabled{% endif %}" id="previous-lesson"style="background-color: #DDF247; color: var(--text-color-black);border: none;">Previous</a>
                        <a href="{% if next_lesson %}{% url 'tutorial_content' slug=slug lesson_slug=next_lesson.slug %}{% endif %}" class="btn btn-primary {% if not next_lesson %}disabled{% endif %}" id="next-lesson"style="background-color: #DDF247; color: var(--text-color-black);border: none;">Next</a>
                    </div>
                    
                    
                </div>
                
                
                <!-- <div class="col-lg-3 col-0"></div> -->
            </div>
        </div>
    </section>

{% endblock %}

{% block internal_script %}
<script>
    $(document).ready(function () {
        var max_height = Math.max(
            $('.tutorial_index').outerHeight(),
            $('.blog_post-content').outerHeight()
        );

        $('.tutorial_index, .blog_post-content').css('min-height', max_height + 'px');
    });
</script>
{% endblock %}

vt_site/templates/tutorial_pages/tutorials.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - Tutorials{% endblock %}
{% block body_content %}


    <!-- <div class="container-fluid blogs-section py-5">
        <div class="my-3">
            <h2 class="features-title">Learn From the Tutorials</h2>
                <div class="input-group position-relative">
                    <input type="search" class="form-control m-0 shadow-none search" placeholder="Search">
                    <span class="input-group-text py-0 bg-info">
                        <i class="bi bi-search"></i>
                    </span>
                    <div class="search_result py-3">No results Found</div>
                </div>

        </div>
    </div> -->

    <section class="container my-3">
        <div class="row">
        <div class="py-4 px-0 position-relative">
            <div class="d-lg-flex align-items-center my-4" style="flex-wrap:wrap">
            <ul id="pills-tab" class="nav nav-tabs fs-5" roms-auto me-2le="tablist">
              <li class="nav-item" role="presentation">
                <a class="nav-link active" id="pills-All-blogs-tab" data-bs-toggle="pill" data-bs-target="#pills-All-blogs" type="button"
                  role="tab" aria-controls="pills-All-blogs" aria-selected="true">All</a>
              </li>
              {% for i in category %}
              <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-cate-{{i.id}}-tab" data-bs-toggle="pill" data-bs-target="#pills-cate-{{i.id}}" type="button"
                  role="tab" aria-controls="pills-cate-{{i.id}}" aria-selected="false" class="d-flex align-items-center justify-content-center"><i class="{{i.icon}} mx-2"></i>{{i.name}}</a>
              </li>
              {% endfor %}
              <i class="fas fa-angle-left"></i>
              <i class="fas fa-angle-right"></i>
            </ul>
            <div class="input-group search-box mt-lg-0 mt-4 me-3 ms-auto">
                <input type="text" class="form-control m-0 shadow-none search" placeholder="Search">
                <span class="input-group-text py-0 bg-info">
                    <i class="bi bi-search"></i>
                </span>
            </div>
            </div>
          
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="pills-All-blogs" role="tabpanel" aria-labelledby="pills-All-blogs-tab">
                <!-- {% if trend_tutorials.exists %}
                <div class="row my-3">
                    <div class="mb-3 d-flex align-items-center more-links">
                        <h4>All Tutorials</h4>
                    </div>
                    
                    {% for i in trend_tutorials %}
                    <div class="col-md-3 col-6 px-md-3 px-2 mb-5">
                        <div class="card tutorials rounded mx-auto" data-aos="fade-in" data-aos-duration="3000">
                            <img src="{{i.image.url}}" alt="{{i.title}}" class="w-100 p-4">
                            <h2 class="pb-3 px-3">{{i.title}}</h2>
                            {% if i.status == 'upcoming' %}
                                <a href="#" class="btn btn-primary my-3 mx-4 disabled"> start </a>
                            {% else %}
                                <a href="{{i.get_absolute_url}}" target="_blank" class="btn btn-primary my-3 mx-4"> start </a>
                            {% endif %}
                            {% if i.status != 'trending' %}
                                <span class="badge text-bg-info">{{i.status}}</span>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %} -->

                {% for cate in category %}
                    {% if cate.tutorial_set.all %}
                    <div class="row my-4">
                        <div class="mb-3 d-flex align-items-center more-links">
                            <h4>{{cate.name}} Tutorials</h4>
                            <a class="more_link ms-auto me-2" data-tab-target="pills-cate-{{cate.id}}-tab">More</a>
                        </div>

                        {% for i in cate.tutorial_set.all %}
                        <div class="col-md-3 col-6 px-md-3 px-2 mb-5">
                            <div class="card tutorials rounded mx-auto" data-aos="fade-in" data-aos-duration="3000">
                                <img src="{{i.image.url}}" alt="{{i.title}}" class="w-100 p-4">
                                <h2 class="pb-3 px-3">{{i.title}}</h2>
                                {% if i.status == 'upcoming' %}
                                <a href="#" class="btn btn-primary my-3 mx-4 disabled" style="color: #1E1E1E;"> > start </a>
                                {% else %}
                                <a href="{{i.get_absolute_url}}"  class="btn btn-primary my-3 mx-4"style="color: #1E1E1E;"> start </a>
                                {% endif %}
                                {% if i.status != 'none' %}
                                    <span class="badge text-bg-info">{{i.status}}</span>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endfor %}
              </div>
      
              {% for cate in category %}
                <div class="tab-pane fade" id="pills-cate-{{cate.id}}" role="tabpanel" aria-labelledby="pills-cate-{{cate.id}}-tab">
                    
                    <div class="row my-4">
                        <div class=" col-12">
                            <div class="row my-4">
                                
                                {% for i in cate.tutorial_set.all %}
                                <div class="col-md-3 col-6 px-md-3 px-2 mb-5">
                                    <div class="card tutorials rounded mx-auto" data-aos="fade-in" data-aos-duration="3000">
                                        <img src="{{i.image.url}}" alt="{{i.title}}" class="w-100 p-4">
                                        <h2 class="pb-3 px-3">{{i.title}}</h2>
                                        {% if i.status == 'upcoming' %}
                                            <a href="#" class="btn btn-primary my-3 mx-4 disabled" style="color: #1E1E1E;"> start </a>
                                        {% else %}
                                        <a href="{{i.get_absolute_url}}" class="btn btn-primary my-3 mx-4" style="color: #1E1E1E;"> start </a>
                                        {% endif %}
                                        {% if i.status != 'none' %}
                                            <span class="badge text-bg-info">{{i.status}}</span>
                                        {% endif %}
                                    </div>
                                </div>
                                {% empty %}
                                    <p class="fs-5 text-info fw-bold">Tutorials in this category will be uploaded soon.</p>
        
                                {% endfor %}
                             
                            </div>
                        </div>

                        <!-- <div class="col-lg-3 col-12">
                            <h4>Top Most Blogs</h4>
                            <div class="py-1">
                                <div class="row py-3 border-bottom">
                                    <div class="col-6">
                                        <img src="{% static './images/python.jpeg' %}" alt="python" style="width:100%">
                                        
                                    </div>
                                    <div class="col-6">
                                        <h3 class="top-blog-titles">Basics of Python program</h3>
                                    </div>
                                </div>
                                
                            </div>

                            <div class="py-1">
                                <div class="row py-3 border-bottom">
                                    <div class="col-6">
                                        <img src="{% static './images/Ethical_Hacking.jpeg' %}" alt="hacking" style="width:100%">
                                        
                                    </div>
                                    <div class="col-6">
                                        <h3 class="top-blog-titles">Zero to Hero Ethical Hacking/h3>
                                    </div>
                                </div>
                                
                            </div>

                            

                            <div class="news-letter my-5">
                                <h2>Join Our NewsLetter</h2>
                                <input type="text" class="form-control m-0 shadow-none my-3" placeholder="subscribe@info.com">
                                <button class="btn my-2">Subscribe</button>
                            </div>
                        </div> -->
                    </div>
                </div>
              {% endfor %}
              
              
            </div>
            
          </div>
        </div>
    </section>

{% endblock %}

{% block internal_script %}
 
    <script>
        const searchInput = document.querySelector('.search');
        const tutorials = Array.from(document.querySelectorAll('.tutorials')); // Assuming tutorials are rendered within elements with the class 'tutorials'

        searchInput.addEventListener('input', function() {
            const searchTerm = searchInput.value.toLowerCase().trim();

            if (searchTerm === '') {
                tutorials.forEach(tutorial => {
                    const tutorial_parent = tutorial.parentNode
                    tutorial.parentNode.style.display = 'block';
                });
            } else {
                tutorials.forEach(tutorial => {
                    const tutorialName = tutorial.textContent.toLowerCase();
                    const match = tutorialName.includes(searchTerm);
                    tutorial.parentNode.style.display = match ? 'block' : 'none';
                });
            }
        });

        const tutorial_link = localStorage.getItem('tutorial_link');
        if(tutorial_link) {
            var tab = document.getElementById(tutorial_link);
            if(tab) {
                tab.click();
                window.scrollTo(0, 0);
            }
            localStorage.removeItem('tutorial_link');
        }
    </script>

{% endblock %}