VulnTech_V3/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vt_site.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'vt_site.views.handel404'

ide/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', editor_view, name='ide'),
]

vt_site/urls.py
from django.conf import settings
from django.urls import include, path
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contactUs', views.contact, name='contact'),
    path('plans', views.plans, name='plans'),
    path('maintenance', views.maintenance, name='maintenance'),
    path('faq', views.faq, name='faq'),
    path('terms_pages/<slug:slug>', views.privacy, name='terms_pages'),
    path('tutorial/', include('tutorial.urls')),
    path('courses/', include('video_courses.urls')),
    path('accounts/', include('account.urls')),
    path('compiler/', include('ide.urls'), name='ide'),
    path('dashboard/', views.my_dashboard, name='my_dashboard'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_courses/models.py
# models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from datetime import timedelta
from account.models import *
from functools import partial
import os
import re
from django.conf import settings

from django.contrib.auth.models import AbstractUser
def validate_file_extension(file, allowed_extensions):
    ext = os.path.splitext(file.name)[1].lower()
    if ext not in allowed_extensions:
        raise ValidationError(
            f"Unsupported file extension. Allowed extensions are: {', '.join(allowed_extensions)}"
        )

# Bind the allowed extensions for course_category images.
validate_category_image = partial(validate_file_extension, allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.bmp'])
# Bind validator for other images
validate_image = partial(validate_file_extension, allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.bmp'])

class course_category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    # New image field for course_category
    image = models.ImageField(
        upload_to='course_category',  # Files saved under MEDIA_ROOT/course_category/
        blank=True,
        null=True,
        validators=[validate_category_image]
    )
    
    def __str__(self) -> str:
        return self.name
    
validate_video = partial(validate_file_extension, allowed_extensions=['.mp4', '.mov', '.avi', '.mkv', '.flv', '.wmv'])

class Courses(models.Model):
    level = (
        ('Beginner', 'Beginner'),
        ('Normal', 'Normal'),
        ('Pro', 'Pro')
    )
    thumbline_image = models.ImageField(upload_to='media/course_imgs', validators=[validate_image])
    intro_video = models.FileField(upload_to='course_videos/', blank=True, null=True, validators=[validate_video])  
    title = models.CharField(max_length=500, unique=True)
    sub_title = models.TextField()
    category = models.ForeignKey(course_category, on_delete=models.CASCADE)
    course_slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    level = models.CharField(choices=level, max_length=100, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    credits = models.IntegerField(null=True, blank=True)
    is_free_course = models.BooleanField(default=False)
    overview = RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field.")

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        first_chapter = self.course_chapter_set.first()
        if first_chapter:
            first_lesson = first_chapter.course_lesson_set.first()
            if first_lesson:
                return reverse("course_content", kwargs={'slug': self.course_slug, 'lesson_slug': first_lesson.slug})
        return reverse("course_content", kwargs={'slug': self.course_slug, 'lesson_slug': None})

class course_FAQ(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, related_name='faqs')
    question = models.CharField(max_length=1000)
    answer = models.CharField(max_length=5000)
    def __str__(self) -> str:
        return self.question

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    model = instance.__class__
    res = model.objects.filter(slug=slug).order_by('-id')
    if res.exists():
        new_slug = f"{slug}-{res.first().id}"
        return create_slug(instance, new_slug=new_slug)
    return slug

def create_course_slug(instance, new_slug=None):
    course_slug = slugify(instance.title)
    if new_slug is not None:
        course_slug = new_slug
    model = instance.__class__
    res = model.objects.filter(course_slug=course_slug).order_by('-id')
    exists = res.exists()
    if exists:
        new_slug = "%s-%s" % (course_slug, res.first().id)
        return create_course_slug(instance, new_slug=new_slug)
    return course_slug

def pre_save_post_course_receiver(sender, instance, *args, **kwargs):
    if not instance.course_slug:
        instance.course_slug = create_course_slug(instance)
pre_save.connect(pre_save_post_course_receiver, Courses)

class course_Chapter(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    def __str__(self):
        return self.title

validate_video_extension = partial(validate_file_extension, allowed_extensions=['.mp4', '.mov', '.avi', '.mkv', '.flv', '.wmv'])

from urllib.parse import urlparse, parse_qs

class course_Lesson(models.Model):
    chapter = models.ForeignKey(course_Chapter, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    video_upload = models.FileField(upload_to='course_videos', blank=True, null=True, validators=[validate_video_extension])
    video_url = models.URLField(max_length=500, blank=True, null=True)
    duration = models.DurationField(default=timedelta(seconds=0))
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("course_content", kwargs={'slug': self.chapter.course.course_slug, 'lesson_slug': self.slug})

    def get_next_lesson(self):
        return self.chapter.course_lesson_set.filter(id__gt=self.id).first()

    def get_previous_lesson(self):
        return self.chapter.course_lesson_set.filter(id__lt=self.id).last()

    def save(self, *args, **kwargs):
        if self.video_url:
            parsed_url = urlparse(self.video_url)
            if "youtu.be" in parsed_url.netloc:
                video_id = parsed_url.path.lstrip("/")
                self.video_url = f"https://www.youtube.com/embed/{video_id}"
            elif "youtube.com" in parsed_url.netloc:
                query_params = parse_qs(parsed_url.query)
                video_id = query_params.get("v", [None])[0]
                if video_id:
                    self.video_url = f"https://www.youtube.com/embed/{video_id}"
        super().save(*args, **kwargs)

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
pre_save.connect(pre_save_post_receiver, course_Lesson)

class Payment(models.Model):
    order_id = models.CharField(max_length=100, blank=True, null=True)
    payment_id = models.CharField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    course = models.ForeignKey(Courses, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name} -- {self.course.title}"

vt_site/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save
from colorfield.fields import ColorField
from phonenumbers import PhoneNumber
from django.core.exceptions import ValidationError
from functools import partial
import os
from django.contrib.auth import get_user_model

from django.conf import settings
def validate_file_extension(file, allowed_extensions):
    ext = os.path.splitext(file.name)[1].lower()
    if ext not in allowed_extensions:
        raise ValidationError(f"Unsupported file extension. Allowed extensions are: {', '.join(allowed_extensions)}")

validate_image = partial(validate_file_extension, allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.bmp'])

class Plan(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    color = ColorField(default='#09c4ff')
    background_color = ColorField(default='#313b44db')

    def __str__(self):
        return self.name

class Accepted_points(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    points = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.plan.name} - {self.points}"

class Normal_points(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    points = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.plan.name} - {self.points}"

class NotAccepted_points(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    points = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.plan.name} - {self.points}"

class Terms_pages(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    content = RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field.")
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def get_absolute_url(self):
        return reverse("terms_pages", kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return self.name

def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    model = instance.__class__
    res = model.objects.filter(slug=slug).order_by('-id')
    exists = res.exists()
    if exists:
        new_slug = "%s-%s" % (slug, res.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Terms_pages)

class Teammate(models.Model):
    pic = models.ImageField(upload_to='media/teammates', null=True, blank=True, validators=[validate_image])
    name = models.CharField(max_length=300)
    role = models.CharField(max_length=500)
    insta_link = models.CharField(max_length=200, null=True, blank=True)
    linkedin_link = models.CharField(max_length=200, null=True, blank=True)
    email_id = models.EmailField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class teammate_skills(models.Model):
    teammate = models.ForeignKey(Teammate, on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)

class site_detail(models.Model):
    home_page_title = models.CharField(max_length=100)
    home_page_desc = models.CharField(max_length=200, blank=True, null=True)
    footer_desc = models.CharField(max_length=500)
    copyright_year = models.CharField(max_length=4)
    contact_mail = models.EmailField()
    contact_number = PhoneNumber()

    circle_animation_image_1 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])
    circle_animation_image_2 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])
    circle_animation_image_3 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])
    circle_animation_image_4 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])
    circle_animation_image_5 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])
    circle_animation_image_6 = models.ImageField(upload_to='media/circle_animation', null=True, validators=[validate_image])

    def split_text(self):
        return self.home_page_title.split(" ")
    
    def __str__(self) -> str:
        return self.home_page_title

class site_details_links(models.Model):
    name = models.ForeignKey(site_detail, on_delete=models.CASCADE)
    icon = models.CharField(max_length=100)
    link = models.CharField(max_length=200)

class FAQ_cate(models.Model):
    icon = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name

class FAQ(models.Model):
    category = models.ForeignKey(FAQ_cate, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)
    answer = models.CharField(max_length=5000)

    def __str__(self) -> str:
        return self.question

class TopCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='media/top_categories', validators=[validate_image])
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("top_category_detail", kwargs={'slug': self.slug})

pre_save.connect(pre_save_post_receiver, TopCategory)
class LoginActivity(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='site_login_activities')
    ip = models.GenericIPAddressField()
    browser = models.CharField(max_length=200)
    os = models.CharField(max_length=200)
    device = models.CharField(max_length=200, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.ip} - {self.browser} on {self.os}"

vt_site/templates/main_elements/aboutus.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - About Us{% endblock %}
{% block body_content %}


<div class="container mt-4">
    <div class="row my-5 pb-3">
        <div class="col-md-6" data-aos="fade-right" data-aos-duration="2000">
            <h2 class="about_us_title mb-3">Our Mission</h2>
            <p class="about_us_content px-2">At Vulntech, our unwavering commitment is to shape a safer, more secure
                digital future for all. We firmly believe that a harmonious fusion of comprehensive education and
                state-of-the-art technology stands as the cornerstone in safeguarding individuals and organizations from
                the ever-evolving landscape of cyber threats. Our resolute mission is to equip you with the
                indispensable knowledge and the most cutting-edge tools, empowering you to rise to the challenge and
                defend against the complexities of the digital age. In our pursuit of digital safety, we leave no stone
                unturned, ensuring that you are well-prepared to face and conquer the intricate realm of cybersecurity.
            </p>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center" data-aos="zoom-in"
            data-aos-duration="2000">
            <img src="{% static './images/Our_Mission.jpg' %}" alt="Our Mission"
                class="img-fluid rounded-circle about_us_img">
        </div>
    </div>
</div>
{% if team %}
<section class="blog-section">
    <div class="container">
        <section class="py-5 py-md-5">
            <div class="row mb-5">
                <h2 class="about_us_title mb-3 text-center" data-aos="fade-right" data-aos-duration="2000">Who We Are
                </h2>
                <p class="about_us_content px-5" data-aos="fade-right-down" data-aos-duration="3000"
                    data-aos-delay="100">We are a team of passionate individuals with expertise in cybersecurity, web
                    development, and UI design. Our combined experience and dedication drive us to develop innovative
                    solutions and educational resources that empower you to stay one step ahead of digital threats.</p>

                <div data-flickity='{"prevNextButtons": true, "cellAlign": "left", "wrapAround": true, "imagesLoaded": true}'
                    data-aos="fade-right-down" data-aos-duration="3000" data-aos-delay="400">
                    {% for member in team %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-12 pt-5 px-3 px-md-4 mb-5">
                        <div class="card profile rounded shadow">
                            {% if member.pic %}
                            <img src="{{member.pic.url}}" alt="Profile_pic"
                                class="card-img-top rounded-circle mx-auto mt-4">
                            {% else %}
                            <img src="{% static './images/icon-profile.png' %}" alt="Profile_pic"
                                class="card-img-top rounded-circle mx-auto mt-4">
                            {% endif %}
                            <div class="card-body text-center">
                                <h4 class="card-title">{{member.name}}</h4>
                                <p class="card-text">{{member.role}}</p>
                                <ul class="list-unstyled list-inline list-social mb-4 mb-md-0">

                                    <li class="list-inline-item list-social-item">
                                        <a href="{% if member.insta_link %} {{member.insta_link}} {% else %} # {% endif %}"
                                            class="text-secondary  rounded-circle">
                                            <i class="bi bi-instagram"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item list-social-item">
                                        <a href="{% if member.linkedin_link %} {{member.linkedin_link}} {% else %} # {% endif %}"
                                            class="text-secondary  rounded-circle">
                                            <i class="bi bi-linkedin"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item list-social-item">
                                        <a href="{% if member.email_id %} mailto:{{member.email_id}} {% else %} # {% endif %}"
                                            class="text-secondary  rounded-circle">
                                            <i class="bi bi-envelope"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-footer m-0 p-3">
                                <h6>Skills</h6>
                                {% for i in member.teammate_skills_set.all %}
                                <span class="badge m-1">{{i.skill}}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    </div>
</section>
{% endif %}
<div class="container">
    <div class="row my-5 pt-5">
        <div class="col-md-6 d-flex align-items-center justify-content-center" data-aos="fade-down-right"
            data-aos-duration="1000">
            <img src="{% static './images/what_we_do.jpg' %}" alt="Our Mission" class="img-fluid rounded mb-5"
                style="transform: skew(5deg);width:45%">
        </div>
        <div class="col-md-6" data-aos="fade-up" data-aos-duration="3000">
            <h2 class="about_us_title mb-3">What We Do</h2>
            <p class="about_us_content px-2">Vulntech stands as a premier authority in the realm of cybersecurity,
                offering a comprehensive array of top-tier courses and resources. Our commitment is unwavering as we
                meticulously craft each offering to educate, train, and equip both individuals and organizations. In an
                era defined by the relentless evolution of cyber threats, we are dedicated to providing you with the
                knowledge and tools necessary to fortify your digital defenses. Our pursuit of excellence is mirrored in
                the broad spectrum of subjects our courses encompass. From laying the foundational principles of
                cybersecurity to delving into the most advanced and sophisticated penetration testing techniques
                available, we leave no stone unturned in preparing you for the complex digital landscape.</p>
            <p class="about_us_content px-2">In our mission to empower, we take pride in offering courses that cater to
                a multitude of needs and skill levels.</p>
        </div>
    </div>


    <div class="row py-5">
        <h2 class="about_us_title mb-5 text-center">Why Choose Vulntech</h2>
        <div class="col-md-3 col-sm-6 col-12">
            <div class="features" data-aos="fade-right" data-aos-duration="1000" data-aos-delay="10">
                <div class="feature-icon rounded-circle">
                    <img src="{% static './images/icon-user.png' %}" alt="instructors">
                </div>
                <h4 class="px-2 fw-bold">Expert Instructors</h4>
                <p class="mt-1">Our courses are created and delivered by industry experts with extensive real-world
                    experience.</p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-12">
            <div class="features" data-aos="fade-right" data-aos-duration="1000" data-aos-delay="100">
                <div class="feature-icon rounded-circle">
                    <img src="{% static './images/icons-knowledge.png' %}" alt="knowledge">
                </div>
                <h4 class="px-2 fw-bold">Cutting-Edge Content</h4>
                <p class="mt-1">We constantly update our content to reflect the latest cybersecurity trends and threats.
                </p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-12">
            <div class="features" data-aos="fade-right" data-aos-duration="1000" data-aos-delay="300">
                <div class="feature-icon rounded-circle">
                    <img src="{% static './images/icon-video_courses.png' %}" alt="learning">
                </div>
                <h4 class="px-2 fw-bold">Interactive Learning</h4>
                <p class="mt-1">Engage with hands-on labs, simulations, and practical exercises to reinforce your
                    knowledge.</p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-12">
            <div class="features" data-aos="fade-right" data-aos-duration="1000" data-aos-delay="500">
                <div class="feature-icon rounded-circle">
                    <i class="fas fa-headset display-1"></i>
                </div>
                <h4 class="px-2 fw-bold">Community Support</h4>
                <p class="mt-1">Join our vibrant community of learners and professionals who share insights and
                    experiences.</p>
            </div>
        </div>


        <p class="about_us_content my-5 px-5">Have questions or want to learn more? Feel free to <a
                href="{% url 'contact' %}">contact us</a> to get in touch with our team.</p>

    </div>

</div>


{% endblock %}

vt_site/templates/main_elements/faq.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - FAQ{% endblock %}
{% block body_content %}


    <div class="container">
        <div class="row mt-5 mb-4 p-0 contact_us_page px-5">
                <h2 class="mb-3 text-center plans-title">FAQ's</h2>
                <p class="fs-6 text-white-50  text-center">Explore our comprehensive FAQs for all the answers you need. Discover solutions and guidance tailored for you.</p>
                <div class="py-4 px-0 position-relative">
                  <ul id="pills-tab" class="nav nav-tabs fs-5 my-4" roms-auto me-2le="tablist">
                    {% for i in faq_category %}
                    <li class="nav-item" role="presentation">
                      <a class="nav-link {% if forloop.first %}active{% endif %}" id="pills-faq-{{i.id}}-tab" data-bs-toggle="pill" data-bs-target="#pills-faq-{{i.id}}"
                        type="button" role="tab" aria-controls="pills-faq-{{i.id}}" aria-selected="false"
                        class="d-flex align-items-center justify-content-center"><i class="{{i.icon}} mx-2"></i>{{i.name}}</a>
                    </li>
                    {% endfor %}
                    <i class="fas fa-angle-left"></i>
                    <i class="fas fa-angle-right"></i>
                  </ul>
              
              
                  {% for cate in faq_category %}
                  <div class="tab-content">
                    <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="pills-faq-{{cate.id}}" role="tabpanel" aria-labelledby="pills-faq-{{cate.id}}-tab">
                        {% for faq in cate.faq_set.all %}
                        <div class="accordion px-md-4 px-0">
                          <div class="accordion-item mb-3">
                            <h2 class="accordion-header">
                              <button class="accordion-button collapsed  shadow-none pe-md-5 pe-4" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse-{{ faq.id }}" aria-expanded="true" aria-controls="collapse-{{ faq.id }}">
                                {{ faq.question }}
                              </button>
                            </h2>
                            <div id="collapse-{{ faq.id }}" class="accordion-collapse collapse">
                              <div class="accordion-body">
                                {{ faq.answer }}
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                      </div>
                    </div>
                    {% endfor %}
                </div>
                
        
        </div>    
    </div>

{% endblock %}

{% block internal_script%}
    <script>
        const toast = document.getElementById('message_toast');
        const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toast);
        $(document).ready(function(){
            if(toast) toastBootstrap.show()
        })
    </script>
{% endblock %}

vt_site/templates/main_elements/terms_pages.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - {{ terms.name }}{% endblock %}
{% block body_content %}
    <div class="container py-5">
        <div class="row justify-content-center mb-5 blog_post-content px-5 py-3">
            <div class="text-center my-3 mb-md-5">
                <h2 class="mb-5 blog-post-title" style="font-size: 3em;" data-aos="fade-right" data-aos-duration="1000">{{ terms.name }}</h2>
                <p class="text-capitalize my-3 w-md-75 w-100" style="text-align: center;">{{ terms.description }}</p>
            </div>
            <div class="py-3 post-content px-5 mx-5">
                {{ terms.content|safe }}
            </div>
        </div>
    </div>

{% endblock %}